export default [
	// Female T-shirts
	{
		id: 1,
		name: 'Red T-shirt',
		img: 'img/gallery/red-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Female',
	},
	{
		id: 2,
		name: 'Pink T-shirt',
		img: 'img/gallery/pink-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Female',
	},
	{
		id: 3,
		name: 'Orange T-shirt',
		img: 'img/gallery/orange-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Female',
	},
	{
		id: 4,
		name: 'Purple T-shirt',
		img: 'img/gallery/purple-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Female',
	},
	// Female Shirts
	{
		id: 5,
		name: 'Shirt',
		img: 'img/gallery/shirt-1.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Female',
	},
	{
		id: 6,
		name: 'Gray Shirt',
		img: 'img/gallery/shirt-2.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Female',
	},
	{
		id: 7,
		name: 'White Shirt',
		img: 'img/gallery/shirt-3.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Female',
	},
	{
		id: 8,
		name: 'Black Shirt',
		img: 'img/gallery/shirt-4.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Female',
	},
	// Female Shoes
	{
		id: 9,
		name: 'Black Shoe',
		img: 'img/gallery/shoe-1.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Female',
	},
	{
		id: 10,
		name: 'Blue Shoe',
		img: 'img/gallery/shoe-2.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Female',
	},
	{
		id: 11,
		name: 'Green Shoe',
		img: 'img/gallery/shoe-3.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Female',
	},
	{
		id: 12,
		name: 'Light Blue Shoe',
		img: 'img/gallery/shoe-4.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Female',
	},
	// Female Watches
	{
		id: 13,
		name: 'Watch One',
		img: 'img/gallery/watch-1.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Female',
	},
	{
		id: 14,
		name: 'Watch Two',
		img: 'img/gallery/watch-2.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Female',
	},
	{
		id: 15,
		name: 'Watch Three',
		img: 'img/gallery/watch-3.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Female',
	},
	{
		id: 16,
		name: 'Watch Four',
		img: 'img/gallery/watch-4.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Female',
	},
	// Female Sunglasses
	{
		id: 17,
		name: 'Sunglass one',
		img: 'img/gallery/sunglass-1.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Female',
	},
	{
		id: 18,
		name: 'Sunglass two',
		img: 'img/gallery/sunglass-2.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Female',
	},
	{
		id: 19,
		name: 'Sunglasses three',
		img: 'img/gallery/sunglass-3.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Female',
	},
	{
		id: 20,
		name: 'Sunglasses four',
		img: 'img/gallery/sunglass-4.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Female',
	},
	// Female Bagpacks
	{
		id: 21,
		name: 'Bagpack one',
		img: 'img/gallery/bagpacks-1.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Female',
	},
	{
		id: 22,
		name: 'Bagpack two',
		img: 'img/gallery/bagpacks-2.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Female',
	},
	{
		id: 23,
		name: 'Bagpack three',
		img: 'img/gallery/bagpacks-3.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Female',
	},
	{
		id: 24,
		name: 'Bagpack four',
		img: 'img/gallery/bagpacks-4.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Female',
	},
	// Male T-shirts
	{
		id: 25,
		name: 'White T-shirt',
		img: 'img/gallery/white-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Male',
	},
	{
		id: 26,
		name: 'Sky T-shirt',
		img: 'img/gallery/sky-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Male',
	},
	{
		id: 27,
		name: 'Yellow T-shirt',
		img: 'img/gallery/yellow-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Male',
	},
	{
		id: 28,
		name: 'Black T-shirt',
		img: 'img/gallery/black-tshirt.png',
		currentPrice: '$175',
		category: 'T-shirt',
		gender: 'Male',
	},
	// Male Shirts
	{
		id: 29,
		name: 'Shirt',
		img: 'img/gallery/shirt-5.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Male',
	},
	{
		id: 30,
		name: 'Gray Shirt',
		img: 'img/gallery/shirt-6.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Male',
	},
	{
		id: 31,
		name: 'White Shirt',
		img: 'img/gallery/shirt-7.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Male',
	},
	{
		id: 32,
		name: 'Black Shirt',
		img: 'img/gallery/shirt-8.png',
		currentPrice: '$175',
		category: 'Shirt',
		gender: 'Male',
	},
	// Male Shoes
	{
		id: 33,
		name: 'Black Shoe',
		img: 'img/gallery/shoe-5.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Male',
	},
	{
		id: 34,
		name: 'Blue Shoe',
		img: 'img/gallery/shoe-6.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Male',
	},
	{
		id: 35,
		name: 'Green Shoe',
		img: 'img/gallery/shoe-7.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Male',
	},
	{
		id: 36,
		name: 'Light Blue Shoe',
		img: 'img/gallery/shoe-8.png',
		currentPrice: '$175',
		category: 'Shoe',
		gender: 'Male',
	},
	// Male Watches
	{
		id: 37,
		name: 'Watch One',
		img: 'img/gallery/watch-5.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Male',
	},
	{
		id: 38,
		name: 'Watch Two',
		img: 'img/gallery/watch-6.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Male',
	},
	{
		id: 39,
		name: 'Watch Three',
		img: 'img/gallery/watch-7.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Male',
	},
	{
		id: 40,
		name: 'Watch Four',
		img: 'img/gallery/watch-8.png',
		currentPrice: '$175',
		category: 'Watch',
		gender: 'Male',
	},
	// Male Sunglasses
	{
		id: 41,
		name: 'Sunglass one',
		img: 'img/gallery/sunglass-5.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Male',
	},
	{
		id: 42,
		name: 'Sunglass two',
		img: 'img/gallery/sunglass-6.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Male',
	},
	{
		id: 43,
		name: 'Sunglasses three',
		img: 'img/gallery/sunglass-7.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Male',
	},
	{
		id: 44,
		name: 'Sunglasses four',
		img: 'img/gallery/sunglass-8.png',
		currentPrice: '$175',
		category: 'Sunglass',
		gender: 'Male',
	},
	// Male Backpacks
	{
		id: 45,
		name: 'Bagpack one',
		img: 'img/gallery/bagpacks-5.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Male',
	},
	{
		id: 46,
		name: 'Bagpack two',
		img: 'img/gallery/bagpacks-6.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Male',
	},
	{
		id: 47,
		name: 'Bagpack three',
		img: 'img/gallery/bagpacks-7.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Male',
	},
	{
		id: 48,
		name: 'Bagpack four',
		img: 'img/gallery/bagpacks-8.png',
		currentPrice: '$175',
		category: 'Bagpack',
		gender: 'Male',
	},
];
